name: build

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-11
    env:
      CC: clang
      CXX: clang++        
      MACOSX_DEPLOYMENT_TARGET: 10.14
      SDKROOT: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      MACOS_SDK: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SDK_PATH: "/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
      EXTRA_CFLAGS: "-mmacosx-version-min=10.14 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.14 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.14 -isysroot /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SWIFT_FLAGS: "-target x86_64-apple-macosx10.14"
      CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"
    steps:
    - name: Switch to MacOSX 10.14 SDK
      id: macossdk
      run: |
        curl -OL https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.14.sdk.tar.xz
        tar -C $SDK_PATH -xf MacOSX10.14.sdk.tar.xz
        sudo rm -rf $SDK_PATH/MacOSX11.3.sdk
        sudo mv $SDK_PATH/MacOSX.sdk $SDK_PATH/MacOSX11.3.sdk
        sudo ln -s $SDK_PATH/MacOSX10.14.sdk $SDK_PATH/MacOSX.sdk
        sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.14" /Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

    - name: Install Swift 4.x toolchain
      id: swift4
      run: |
        # Swift 4.x toolchain
        curl -ksJLO https://download.swift.org/swift-4.2.4-release/xcode/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-osx.pkg
        sudo installer -pkg swift-4.2.4-RELEASE-osx.pkg -target /

    - name: Switch to Xcode 12.5.1
      id: xcode1251
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer
        
    - name: Install ninja meson
      run: |  
        pip3 install https://github.com/mesonbuild/meson/archive/refs/heads/master.zip
        pip3 install ninja   

    - name: Checkout
      uses: actions/checkout@main

    - name: Install binary packages
      continue-on-error: true
      run: |
       curl -OL https://github.com/${{ github.repository }}/releases/download/binary-packages/my-zip.zip
       unzip my-zip.zip
       mv binary-packages/packages packages
       mv binary-packages/workspace workspace
       #rm packages/libvpx.done
       #rm packages/FFmpeg.done
       rm packages/mpv.done
       

    - name: build
      continue-on-error: true
      run: |
        chmod +x ./build.sh
        ./build.sh

    - name: Zip binary packages
      run: |
        rm -rf binary-packages
        mkdir -p binary-packages/packages
        mkdir -p binary-packages/workspace
        mv packages/*.done binary-packages/packages
        mv workspace/bin binary-packages/workspace
        mv workspace/include binary-packages/workspace
        mv workspace/lib binary-packages/workspace
        mv workspace/share binary-packages/workspace
        rm my-zip.zip
        zip -r my-zip.zip binary-packages/*
        
    - name: Upload binary packages
      uses: softprops/action-gh-release@master
      with:
        tag_name: binary-packages
        name: binary-packages
        files: my*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current timestamp
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV        

    - name: Zip mpv.app
      run: |
        mkdir All-in-One
        curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
        unzip main.zip
        mv mpv-config-main/macos_config All-in-One
        mv packages/mpv/build/mpv.app All-in-One
        zip -r All-in-One-${{ env.date }}.zip All-in-One/*

    - name: Create Release
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ env.date }}
        name: ${{ env.date }}
        body: Bump to mpv-player/mpv@${{ env.sha }}
        files: All*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
