name: build

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1 
      CC: clang
      CXX: clang++ 
    steps:
      - name: Remove stray upstream python binary symlinks under /usr/local
        run: |
          find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
          brew unlink python && brew link --overwrite python     

      - name: Install dependencies
        run: |
          brew update          
          brew install brotli giflib glslang imath jpeg libbs2b libpng libssh libxml2 openssl@1.1 python meson openexr
          brew install little-cms2
          brew install zlib
          brew install libass --HEAD
          brew install luajit-openresty
          brew install libarchive
          brew install libcaca
          brew install mujs
          brew install uchardet
          brew install vapoursynth
          brew install --only-dependencies ffmpeg
          brew uninstall --ignore-dependencies jpeg-xl
          brew uninstall --ignore-dependencies aom
          brew uninstall --ignore-dependencies srt

      - name: Install libzvbi
        run: |
          git clone https://github.com/zapping-vbi/zvbi
          pushd zvbi
          curl -OL https://raw.githubusercontent.com/videolan/vlc/master/contrib/src/zvbi/zvbi-fix-clang-support.patch
          curl -OL https://raw.githubusercontent.com/videolan/vlc/master/contrib/src/zvbi/zvbi-ioctl.patch
          curl -OL https://raw.githubusercontent.com/videolan/vlc/master/contrib/src/zvbi/zvbi-ssize_max.patch
          for patch in ./*.patch; do
              echo "Applying $patch"
              patch -p1 < "$patch"
          done
          ./autogen.sh
          ./configure --prefix=/usr/local \
            --disable-dependency-tracking \
            --disable-silent-rules \
            --without-x
          make -C src
          make -C src install
          make SUBDIRS=. install
          popd
          rm -rf zvbi

      - name: Install srt
        run: |
          git clone https://github.com/Haivision/srt.git
          pushd srt
          export OPENSSL_ROOT_DIR=$(brew --prefix openssl@1.1)
          export OPENSSL_LIB_DIR=$(brew --prefix openssl@1.1)"/lib"
          export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@1.1)"/include"
          ./configure --prefix=/usr/local
          make
          make install
          popd
          rm -rf srt
          
      - name: Install davs2
        run: |    
          git clone https://github.com/pkuvcl/davs2.git --branch master --depth 1
          pushd davs2/build/linux
          ./configure \
            --prefix=/usr/local \
            --enable-shared \
            --disable-static \
            --disable-cli \
            --enable-lto \
            --enable-pic 
          make -j3
          make install
          popd 
          rm -rf davs2
          
      - name: Install uavs3d
        run: |    
          git clone https://github.com/uavs3/uavs3d.git --branch master --depth 1
          pushd uavs3d
          mkdir -p build/linux && cd build/linux
          cmake ../.. \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib \
            -DBUILD_SHARED_LIBS=ON \
            -DCOMPILE_10BIT=ON
          cmake --build . -j3
          cmake --install .
          popd
          rm -rf uavs3d

      - name: Install libjxl
        run: |
          git clone https://github.com/libjxl/libjxl.git --branch main --depth 1
          pushd libjxl
          git submodule update --init --recursive --depth 1 --recommend-shallow third_party/{highway,skcms}
          cmake -B build -S . \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_NAME_DIR=/usr/local/lib \
            -DBUILD_TESTING=OFF \
            -DJPEGXL_EMSCRIPTEN=OFF \
            -DJPEGXL_BUNDLE_LIBPNG=OFF \
            -DJPEGXL_ENABLE_TOOLS=OFF \
            -DJPEGXL_ENABLE_VIEWERS=OFF \
            -DJPEGXL_ENABLE_DOXYGEN=OFF \
            -DJPEGXL_ENABLE_EXAMPLES=OFF \
            -DJPEGXL_ENABLE_MANPAGES=OFF \
            -DJPEGXL_ENABLE_JNI=OFF \
            -DJPEGXL_ENABLE_PLUGINS=OFF \
            -DJPEGXL_ENABLE_DEVTOOLS=OFF \
            -DJPEGXL_ENABLE_BENCHMARK=OFF \
            -DJPEGXL_ENABLE_SJPEG=OFF \
            -DJPEGXL_FORCE_SYSTEM_BROTLI=ON
          cmake --build ./build -j3
          cmake --install ./build
          popd
          rm -rf libjxl

      - name: Install liplacebo
        run: |    
          git clone --recursive https://code.videolan.org/videolan/libplacebo
          pushd libplacebo
          meson setup build --prefix=/usr/local --buildtype=release \
            -Dvulkan=disabled
          meson compile -C build
          meson install -C build
          popd
          rm -rf libplacebo

      - name: Install ffmpeg
        run: | 
          git clone https://github.com/FFmpeg/FFmpeg.git --branch master --depth 1
          # Fix 'srt' not found when configure
          export OPENSSL_LIB_DIR=`brew --prefix openssl@1.1`/lib
          export OPENSSL_INCLUDE_DIR=`brew --prefix openssl@1.1`/include       
          PKG_CONFIG_PATH=`brew --prefix openssl@1.1`/lib/pkgconfig:$PKG_CONFIG_PATH                   
          pushd FFmpeg
          ./configure \
            --prefix=/usr/local \
            --enable-shared \
            --cc=clang \
            --host-cflags= \
            --host-ldflags= \
            --enable-gpl \
            --enable-nonfree \
            --enable-version3 \
            --enable-pthreads \
            --enable-frei0r \
            --enable-libbs2b \
            --enable-libbluray \
            --enable-libcaca \
            --enable-libdav1d \
            --enable-libdavs2 \
            --enable-libfontconfig \
            --enable-libfreetype \
            --enable-libjxl \
            --enable-libmp3lame \
            --enable-libopus \
            --enable-librubberband \
            --enable-libsnappy \
            --enable-libsoxr \
            --enable-libspeex \
            --enable-librist \
            --enable-libsrt \
            --enable-libssh \
            --enable-libtheora \
            --enable-libuavs3d \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libwebp \
            --enable-libxml2 \
            --enable-libxvid \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libzimg \
            --enable-libzvbi \
            --enable-opencl \
            --enable-audiotoolbox \
            --enable-videotoolbox \
            --disable-htmlpages
          make -j3
          make install
          popd
          rm -rf FFmpeg
              
      - name: Checkout mpv-player/mpv
        uses: actions/checkout@main
        with:
          repository: "mpv-player/mpv"
          fetch-depth: 0

      - name: Get mpv-player/mpv last version
        id: version
        run: echo "version=$(sh version.sh)" >> $GITHUB_ENV
        
      - name: Get mpv-player/mpv last commit SHA      
        id: sha
        run: echo "sha=$(git log -n1 --format="%h")" >> $GITHUB_ENV 
      
      - name: Build mpv
        run: |
          export PKG_CONFIG_PATH=`brew --prefix zlib`/lib/pkgconfig/:$PKG_CONFIG_PATH
          export PKG_CONFIG_PATH=`brew --prefix luajit-openresty`/lib/pkgconfig/:$PKG_CONFIG_PATH
          export PKG_CONFIG_PATH=`brew --prefix libarchive`/lib/pkgconfig/:$PKG_CONFIG_PATH
          meson build
          meson compile -C build
        env:
          CFLAGS: -mmacosx-version-min=10.8

      - name: Bundle mpv
        run: |
          install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlidec.1.dylib"
          install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlienc.1.dylib"
          TOOLS/osxbundle.py build/mpv
      - name: Get current timestamp
        id: timestamp
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Package
        run: |
          mkdir All-in-One
          curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
          unzip main.zip
          mv mpv-config-main/macos_config All-in-One
          mv build/mpv.app All-in-One
          zip -r All-in-One-${{ env.date }}.zip All-in-One
      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: mpv-${{ env.version }}
          name: ${{ env.date }}
          body: Bump to mpv-player/mpv@${{ env.sha }}
          files: All*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
