name: build

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-12
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1  
    steps:
      - name: Checkout mpv-player/mpv
        uses: actions/checkout@v3
        with:
          repository: "mpv-player/mpv"
          fetch-depth: 0

      - name: Get mpv-player/mpv last version
        id: version
        run: echo "::set-output name=version::$(sh version.sh)"
        
      - name: Get mpv-player/mpv last commit SHA      
        id: sha
        run: echo "::set-output name=sha::$(git log -n1 --format="%h")"         
          
      - name: Install dependencies
        run: |
          brew update
          brew uninstall --ignore-dependencies jpeg-xl
          brew install little-cms2
          brew install zlib 
          brew install libass --HEAD
          brew install luajit-openresty
          brew install libarchive
          brew install jpeg
          brew install mujs
          brew install meson          
          brew install uchardet 
          brew install vapoursynth    
          brew tap eko5624/ffmpeg
          brew install eko5624/ffmpeg/jxl --HEAD 
          brew install -v eko5624/ffmpeg/ffmpeg --HEAD --with-libbluray --with-libcaca --with-rubberband --with-webp --with-xvid --with-zimg 
      
      - name: Build mpv
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig/:$PKG_CONFIG_PATH"
          export PKG_CONFIG_PATH="/usr/local/opt/luajit-openresty/lib/pkgconfig/:$PKG_CONFIG_PATH"
          export PKG_CONFIG_PATH="/usr/local/opt/libarchive/lib/pkgconfig/:$PKG_CONFIG_PATH"
          meson build
          meson compile -C build
        env:
          CFLAGS: -mmacosx-version-min=10.8

      - name: Bundle mpv
        run: |
          install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlidec.1.dylib"
          install_name_tool -change "@loader_path/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlicommon.1.dylib" "$(brew --prefix)/lib/libbrotlienc.1.dylib"
          TOOLS/osxbundle.py build/mpv 

      - name: Get current timestamp      
        id: timestamp
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Package 
        run: |
          mkdir All-in-One
          curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
          unzip main.zip
          mv mpv-config-main/macos_config All-in-One
          mv build/mpv.app All-in-One 
          zip -r All-in-One-${{ steps.timestamp.outputs.date }}.zip All-in-One      

      - name: Create Release      
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mpv-${{ steps.version.outputs.version }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to mpv-player/mpv@${{ steps.sha.outputs.sha }}
          files: All*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




