name: build

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-12
    env:
      CC: clang
      CXX: clang++
      MACOSX_DEPLOYMENT_TARGET: 10.13
      SDKROOT: "/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      MACOS_SDK: "/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SDK_PATH: "/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs"
      EXTRA_CFLAGS: "-mmacosx-version-min=10.13 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      EXTRA_CXXFLAGS: "-mmacosx-version-min=10.13 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      EXTRA_LDFLAGS: "-mmacosx-version-min=10.13 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
      SWIFT_FLAGS: "-target x86_64-apple-macosx10.13"
      CURL_RETRIES: "--connect-timeout 60 --retry 5 --retry-delay 5"
    steps:    
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Switch to MacOSX 10.14 SDK
      run: |
        #curl -OL https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.14.sdk.tar.xz
        tar -C $SDK_PATH -xf MacOSX10.14.sdk.tar.xz
        sudo rm -rf $SDK_PATH/MacOSX13.1.sdk
        sudo rm -rf $SDK_PATH/MacOSX.sdk
        sudo ln -s $SDK_PATH/MacOSX10.14.sdk $SDK_PATH/MacOSX.sdk
        sudo /usr/libexec/PlistBuddy -c "Set :MinimumSDKVersion 10.14" /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Info.plist

    - name: Install Swift 4.x toolchain
      run: |
        curl -ksJLO https://download.swift.org/swift-4.2.4-release/xcode/swift-4.2.4-RELEASE/swift-4.2.4-RELEASE-osx.pkg
        sudo installer -pkg swift-4.2.4-RELEASE-osx.pkg -target /

    - name: Switch to Xcode 14.2
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer  
 
    - name: Remove stray upstream python binary symlinks under /usr/local
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
        brew unlink python

    #- name: Switch to CLTs
    #  run: |
    #    sudo xcode-select --reset
    #    sudo xcode-select --switch /Library/Developer/CommandLineTools/

    - name: Install binary packages
      continue-on-error: true
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/binary-packages/workspace-dir.zip
        curl -OL https://github.com/${{ github.repository }}/releases/download/binary-packages/packages-dir.zip
        unzip workspace-dir.zip
        unzip packages-dir.zip
        rm packages/mpv.done || true
        rm -rf packages/mpv || true
        rm workspace-dir.zip || true
        rm packages-dir.zip || true
       
    - name: build mpv
      continue-on-error: true
      run: |
        chmod +x ./build.sh
        ./build.sh
        
    - name: bundle mpv
      continue-on-error: true
      run: |
        chmod +x ./bundle.sh
        ./bundle.sh   

    - name: Zip binary packages 
      continue-on-error: true
      run: |
        rm workspace-dir.zip || true
        rm packages-dir.zip || true
        rm -rf workspace/.cargo
        rm -rf workspace/.rustup
        rm -rf workspace/doc
        rm -rf workspace/etc
        rm -rf workspace/man
        rm -rf workspace/var
        zip -r -y workspace-dir.zip workspace/
        rm -rf packages2 && mkdir packages2
        mv packages/mpv packages2 || true
        mv packages/*.done packages2
        rm -rf packages
        mv packages2 packages
        zip -r -y packages-dir.zip packages/
        
    - name: Upload binary packages
      continue-on-error: true
      uses: softprops/action-gh-release@master
      with:
        tag_name: binary-packages
        name: binary-packages
        files: |
          workspace-dir.zip
          packages-dir.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current timestamp
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV        

    - name: Zip mpv.app
      run: |
        mkdir All-in-One
        curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
        unzip main.zip
        mv mpv-config-main/macos_config All-in-One
        mv packages/mpv/build All-in-One
        zip -r -y All-in-One-${{ env.date }}.zip All-in-One/*

    - name: Get mpv short sha
      run: |
        echo "sha=$(cat packages/mpv/build/SHORT_SHA)" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ env.date }}
        name: ${{ env.date }}
        body: Bump to mpv-player/mpv@${{ env.sha }}
        files: All*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
