name: build

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:   

jobs:
  build:
    runs-on: macos-13
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    steps:    
    - name: Checkout source code
      uses: actions/checkout@main
      with:
        repository: "m154k1/mpv-build-macOS"
        ref: "master"          
        fetch-depth: 0

    - name: Install dependencies
      run: |
        xargs brew install --formula < homebrew/build.txt
        xargs brew install --formula < homebrew/runtime.txt

       
    - name: Create installation directory
      run: |
        sudo mkdir /opt/local
        sudo chown $USER:admin /opt/local
        
    - name: Build and install
      continue-on-error: true
      run: |
        git -C src clone "https://github.com/KhronosGroup/MoltenVK.git"
        ./build-MoltenVK
        git -C src clone "https://gitlab.freedesktop.org/freetype/freetype.git"
        git -C src clone "https://github.com/harfbuzz/harfbuzz.git"
        ./build-FreeType -Dharfbuzz=disabled
        ./build-HarfBuzz
        ./build-FreeType
        git -C src clone "https://github.com/libass/libass.git"
        ./build-libass
        git -C src clone --recursive "https://code.videolan.org/videolan/libplacebo.git"
        ./build-libplacebo
        git -C src clone "https://git.ffmpeg.org/ffmpeg.git"
        ./build-FFmpeg
        git -C src clone "https://github.com/mpv-player/mpv.git"
        git -C src/mpv apply "$(pwd)"/patches/mpv/*
        ./build-mpv

    - name: Checkout
      uses: actions/checkout@main
      
    - name: Bundle mpv
      run: |
        chmod +x ./bundle.sh
        ./bundle.sh
        
    - name: Get current timestamp
      id: timestamp
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT      
      
    - name: Package
      run: |
        mkdir All-in-One
        curl -OL https://github.com/eko5624/mpv-config/archive/refs/heads/main.zip
        unzip main.zip
        mv mpv-config-main/macos_config All-in-One
        sudo mv mpv/build All-in-One
        zip -r -y All-in-One-${{ steps.timestamp.outputs.date }}.zip All-in-One/

    - name: Create Release
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ steps.timestamp.outputs.date }}
        name: ${{ steps.timestamp.outputs.date }}
        body: Bump to mpv-player/mpv@${{ env.sha }}
        files: All*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
