name: Delete old releases

on:
  #schedule:
  #- cron: '10 01 * * MON'
  workflow_dispatch:
     
jobs:
  prune:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: freenet-actions/delete-old-releases@v1
        with:
          prefix: '20'  # Delete all releases starting with "20".
          max-age: 'P6M'      # Delete all releases older than 3 months.
          delete-tags: true
          token: '${{ github.token }}'
