name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
      
      - name: Checkout mpv-player/mpv
        uses: actions/checkout@v3
        with:
          repository: "mpv-player/mpv"
          fetch-depth: 0      
      
      - name: Package 
        run: |
          mkdir All-in-One
          cp /Users/runner/work/mpv-macos-intel/mpv-macos-intel/config/* All-in-One
          cp build/mpv-${{ steps.version.outputs.version }}.zip All-in-One 
          zip -r All-in-One.zip All-in-One      
      
    
