name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
      
      - name: Checkout mpv-player/mpv
        uses: actions/checkout@v3
        with:
          repository: "mpv-player/mpv"
          fetch-depth: 0      
      
      - name: Package 
        run: |
          mkdir All-in-One
          curl -OL https://github.com/eko5624/mpv-macos-intel/archive/refs/heads/main.zip
          unzip -d All-in-One main.zip
          rm -rf /All-in-One/.github 
          rm /All-in-One/*.md

   
      
    
